### ISSUE TITLE
暗黑模式下，底部状态栏的文字颜色改成亮色

### ISSUE THREAD

**Issue by frostime** [TinkMingKing/siyuan-themes-wpslite#1]
这是 WPS Lite

![image](https://github.com/TinkMingKing/siyuan-themes-wpslite/assets/27268127/5b4596f0-346d-40fc-b0d8-4588601dc162)

这是默认

![image](https://github.com/TinkMingKing/siyuan-themes-wpslite/assets/27268127/65032338-22ad-486d-9385-9d0c7be53fda)

**Comment by TinkMingKing** [comment]
忘记改了……
